### Get All Deduction Salary Data
GET  http://localhost:5000/deduction_data

### Create Deduction Data
POST  http://localhost:5000/deduction_data
Content-Type: application/json

{
    "id" : 1 ,
    "deduction": "absent",
    "deduction_amt": 2000
}

### UPDATE Deduction Data
PATCH  http://localhost:5000/deduction_data/update/3
Content-Type: application/json

{
    "deduction" : "updated 1",
    "deduction_amt" : 9999
}

### DELETE Deduction Data
DELETE http://localhost:5000/deduction_data/3